apiVersion: backstage.io/v1alpha1
kind: {{cookiecutter.kind}}
metadata:
  name: {{cookiecutter.name}}
  
spec:
  type: service
  lifecycle: experimental
  owner: {{cookiecutter.owner}}
  system: {{cookiecutter.system}}
  {% if cookiecutter.kind == "Component" %}
  dependsOn:
    - {{cookiecutter.depends_on}}
  dependencyOf:
    - {{cookiecutter.dependency_of}}
  providesApis:
    - {{cookiecutter.providesApis}}
  {% endif %}

